### ISSUE TITLE
Trailing comma causes syntax error

### ISSUE THREAD

**Issue by tterhaarlaudert** [OXIDprojects/easycredit-module#10]
https://github.com/OXIDprojects/easycredit-module/blob/43f4213bc2540fca6f61c94a51ff82c2955b99a2/Core/Di/EasyCreditDicFactory.php#L44

Tested with OXID EE 6.1 (PHP 7.2)

**Comment by mariolorenz** [comment]
fixed by #11

**Comment by mariolorenz** [comment]
@tterhaarlaudert : Thank you!
