### ISSUE TITLE
Support backwards compatibility for PHP 7.2

### ISSUE THREAD

**Issue by tterhaarlaudert** [OXIDprojects/easycredit-module#17]
We would like to use this module in an OXID shop that is still running on PHP 7.2.

Currently there are 3 lines of code that are working with at least PHP 7.3 only, because of the following problem:

`Trailing comma in function calls is only available since PHP 7.3`

1. https://github.com/OXIDprojects/easycredit-module/blob/2df6ed6944b25368885bfbac91934fe9583e5b8b/Application/Controller/Admin/EasyCreditOrderEasyCreditController.php#L236
2. https://github.com/OXIDprojects/easycredit-module/blob/2df6ed6944b25368885bfbac91934fe9583e5b8b/Application/Model/EasyCreditTradingApiAccess.php#L70
3. https://github.com/OXIDprojects/easycredit-module/blob/2df6ed6944b25368885bfbac91934fe9583e5b8b/Application/Model/EasyCreditTradingApiAccess.php#L119

Can you please remove the trailing commas to support backwards compatibility for PHP 7.2?

**Comment by mariolorenz** [comment]
would be fixed by [PSEC-77](https://github.com/OXIDprojects/easycredit-module/tree/PSEC-77)
